services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    build: requirements/nginx/
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/codekiwi/data/wordpress
      o: bind

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/codekiwi/data/mariadb
      o: bind